AWSTemplateFormatVersion: 2010-09-09

Description: This template creates an RDS database with MYSQL 8.0 engine 

Resources:   
  DatabaseInstance:
    Type: AWS::RDS::DBInstance
    DeletionPolicy: Delete
    Properties:
      AllocatedStorage: 20
      AvailabilityZone: !Select [ 0, !GetAZs  '' ]
      BackupRetentionPeriod: 0
      DBInstanceClass: db.t2.micro
      DBInstanceIdentifier: rds-db
      DBName: applicationdb
      Engine: MySQL
      EngineVersion: 8.0.28
      MasterUsername: azeezs
      MasterUserPassword: azeezs123
      MultiAZ: false
      VPCSecurityGroups:
        - sg-a06262b8

# AWS Doc
# https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/dynamic-references.html#dynamic-references-ssm-secure-strings